const data = {
  products: [
    {
      name: 'Titolo',
      slug: 'titolo',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'titolo1',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'titolo2',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'titolo3',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'titolo4',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'titolo5',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 60,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'titolo6',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'titolo7',
      codiceArticolo: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      description: 'Biglietti da visita personalizzati',
    },
    {
      name: 'Titolo',
      slug: 'buste1',
      codiceArticolo: 'lorem ipsum',
      image: '/images/buste.jpg',
      category: 'Buste',
      price: 5,
      countInStock: 7,
      description: 'Buste per spedizioni',
    },
    {
      name: 'Titolo',
      slug: 'buste2',
      codiceArticolo: 'lorem ipsum',
      image: '/images/buste.jpg',
      category: 'Buste',
      price: 5,
      countInStock: 7,
      description: 'Buste per spedizioni',
    },
    {
      name: 'Titolo',
      slug: 'buste3',
      codiceArticolo: 'lorem ipsum',
      image: '/images/buste.jpg',
      category: 'Buste',
      price: 5,
      countInStock: 7,
      description: 'Buste per spedizioni',
    },
  ],
};

export default data;
