const data = {
  products: [
    {
      name: 'Titolo',
      slug: 'titolo',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac dui in nulla facilisis finibus. Fusce scelerisque leo sed mauris tincidunt, vitae ultricies magna facilisis.',
    },
    {
      name: 'Titolo',
      slug: 'titolo1',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac dui in nulla facilisis finibus. Fusce scelerisque leo sed mauris tincidunt, vitae ultricies magna facilisis.',
    },
    {
      name: 'Titolo',
      slug: 'titolo2',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac dui in nulla facilisis finibus. Fusce scelerisque leo sed mauris tincidunt, vitae ultricies magna facilisis.',
    },
    {
      name: 'Titolo',
      slug: 'titolo3',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 4.5,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac dui in nulla facilisis finibus. Fusce scelerisque leo sed mauris tincidunt, vitae ultricies magna facilisis.',
    },
    {
      name: 'Titolo',
      slug: 'titolo4',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 7.5,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac dui in nulla facilisis finibus. Fusce scelerisque leo sed mauris tincidunt, vitae ultricies magna facilisis.',
    },
    {
      name: 'Titolo',
      slug: 'titolo5',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 60,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac dui in nulla facilisis finibus. Fusce scelerisque leo sed mauris tincidunt, vitae ultricies magna facilisis.',
    },
    {
      name: 'Titolo',
      slug: 'titolo6',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac dui in nulla facilisis finibus. Fusce scelerisque leo sed mauris tincidunt, vitae ultricies magna facilisis.',
    },
    {
      name: 'Titolo',
      slug: 'titolo7',
      code: 'lorem ipsum',
      image: '/images/biglietti.jpg',
      category: 'biglietti-da-visita',
      price: 70,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Biglietti Fuori Sede',
    },
    {
      name: 'Titolo',
      slug: 'buste1',
      code: 'lorem ipsum',
      image: '/images/buste.jpg',
      category: 'buste',
      price: 5,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Buste per spedizioni',
    },
    {
      name: 'Titolo',
      slug: 'buste2',
      code: 'lorem ipsum',
      image: '/images/buste.jpg',
      category: 'buste',
      price: 5,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Buste per spedizioni',
    },
    {
      name: 'Titolo',
      slug: 'buste3',
      code: 'lorem ipsum',
      image: '/images/buste.jpg',
      category: 'buste',
      price: 5,
      countInStock: 7,
      quantity: 'Confezione da 100',
      description: 'Buste per spedizioni',
    },
  ],
};

export default data;
